[project]
name = "streamlit-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "jupyterlab>=4.4.7",
    "matplotlib>=3.9.4",
    "scikit-learn>=1.6.1",
    "streamlit>=1.49.1",
]
